name: "TFSec Terraform"

on:
  push:
    branches:

  pull_request:
  
  workflow_dispatch:


jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://agent:${GH_TOKEN}@github.com/Maersk-Global".insteadOf "https://github.com/Maersk-Global"
        env:
          GH_TOKEN: ${{ secrets.MYSECRET }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          sarif_file: tfsec.sarif
          
      - name: Inspect action SARIF report
        run: cat tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif
